
import './globals.css'
import { Inter } from 'next/font/google'
import Home from './page'
import Section2 from './section2'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className='w-screen h-screen'>
     <Home/>
     <Section2/>
     </div>
    </html>
  )
}
