"use client";
import "./globals.css";
import { Inter,Roboto } from "next/font/google";
import Header from "./header";
import Footer from "./footer";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"],
weight: ['100','200','300','400','500','600','700','800','900']
 });


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <main className={`flex  flex-col items-center justify-between ${inter.className} `}>
        <div className="w-full h-full">
          {children}
        </div>
      </main>
    </html>
  );
}
